# Generated by Django 4.2.7 on 2023-12-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('certified', models.BooleanField()),
                ('halal', models.BooleanField()),
                ('alcohol', models.BooleanField()),
                ('rating', models.FloatField()),
                ('prayer_facility', models.BooleanField()),
                ('address', models.TextField()),
            ],
        ),
    ]
