# Generated by Django 4.2.7 on 2023-12-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
            ],
        ),
    ]
